create table roles (
  id bigint not null generated by default as identity
, name varchar(127) not null
, description varchar(511) not null
);
alter table roles add constraint pk_roles primary key(id);
insert into roles(name, description) values
 ('Roles','Roles')--1
,('Users','Users')--2
,('User Groups','User Groups')--3
;

create table userGroups (
  id smallint not null generated by default as identity
, name varchar(63) not null
);
alter table userGroups add constraint pk_userGroups primary key(id);
insert into userGroups(name) values ('ADMIN');--1

create table roles_groups (
  roleId bigint not null
, groupId smallint not null
);
alter table roles_groups add constraint pk_roles_groups primary key(roleId, groupId);
alter table roles_groups add constraint fk_roles_groups_roles foreign key(roleId) references roles(id);
alter table roles_groups add constraint fk_roles_groups_userGroups foreign key(groupId) references userGroups(id);
insert into roles_groups(groupId, roleId) values
 (1,1)
,(1,2)
,(1,3)
;

create table users (
  id bigint not null generated by default as identity
, personId bigint default null
, username varchar(63) not null
, password varchar(60) not null
, email varchar(95) not null
);
alter table users add constraint pk_users primary key(id);
create unique index ix_users_email on users(email asc);

create table users_groups (
  userId bigint not null
, groupId smallint not null
);
alter table users_groups add constraint pk_users_groups primary key(userId, groupId);
alter table users_groups add constraint fk_users_groups_users foreign key(userId) references users(id);
alter table users_groups add constraint fk_users_groups_groups foreign key(groupId) references userGroups(id);

insert into users(email,password,personId,username) values
 ('a1@a.co','p@ssw0rD',NULL,'a1')--1
,('a2@a.co','p@ssw0rD',NULL,'a2')--2
;
insert into users_groups(userId,groupId) values(1,1),(2,1);
